name: Deploy Site

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
    - name: Get files
      uses: actions/checkout@v2.3.4
  
    - name: Deploy site
      uses: cinderblockgames/ftp-action@v1.2.2
      with:
        # required
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # optional
        source: docs
        skipDirectories: .github|.well-known|cert
        skipUnchanged: true
        
